server:
  port: 8200
spring:
  application:
    name: tcloud-gateway-zuulserver

eureka:
    instance:
      hostname: localhost   # 指定该Eureka实例的主机名
      prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:1112/eureka/